### PR TITLE
add: the tips for `find-definitions` command.

### PR DESCRIPTION
**Pull request by sakurawald**
Related issue: https://github.com/lem-project/lem/issues/361

### CODE REVIEW

**Comment by vindarel** [comment]
Thank you very much for adding documentation.

How did you install Lem yourself, with Roswell? Then, specify that this command is for Roswell users. 

We don't need to run this command if we installed SBCL differently, for example from Debian's package manager. It works for me (for example M-. on `defun`, `defmacro` etc).

**Comment by sakurawald** [comment]
> Thank you very much for adding documentation.
> 
> How did you install Lem yourself, with Roswell? Then, specify that this command is for Roswell users, I suppose we don't need to run this command if we installed SBCL differently.

My roswell is installed via source, folloing the manual to make the `sdl2 version lem` binary file.

**Comment by sakurawald** [comment]
I am not very sure about this. Can you see this issue ?
https://github.com/lem-project/lem/issues/1592

**Comment by sakurawald** [comment]
I found the difference:
If you use `find-definitions` command in the `lisp repl` used by `lem editor` itself, then it will locate the `sbcl source` in `/usr/share/sbcl-source` direcoty. (I am using linux, if you install sbcl via `yay -S sbcl`, then it will download the sbcl-source to this location).

The strange thing is that: if you start `lisp repl` using `M-x slime <ret>`, then the `find-definitions` command will try to locate `sbcl source` in `/tmp/sbcl/src/code`.

**Pull request closed without merging**
